package com.cis.paseaproduccionweb.beans;
// Generated 18/06/2015 11:24:36 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PpFormularios generated by hbm2java
 */
public class PpFormularios  implements java.io.Serializable {


     private BigDecimal formularioId;
     private String flagEstado;
     private String flagUso;
     private String descFormulario;
     private String nombreFormulario;
     private BigDecimal ppsubmenuSubmenuId;
     private BigDecimal ppusuarioUsuarioId;

    public PpFormularios() {
    }

	
    public PpFormularios(BigDecimal formularioId, BigDecimal ppsubmenuSubmenuId) {
        this.formularioId = formularioId;
        this.ppsubmenuSubmenuId = ppsubmenuSubmenuId;
    }
    public PpFormularios(BigDecimal formularioId, String flagEstado, String flagUso, String descFormulario, String nombreFormulario, BigDecimal ppsubmenuSubmenuId, BigDecimal ppusuarioUsuarioId) {
       this.formularioId = formularioId;
       this.flagEstado = flagEstado;
       this.flagUso = flagUso;
       this.descFormulario = descFormulario;
       this.nombreFormulario = nombreFormulario;
       this.ppsubmenuSubmenuId = ppsubmenuSubmenuId;
       this.ppusuarioUsuarioId = ppusuarioUsuarioId;
    }
   
    public BigDecimal getFormularioId() {
        return this.formularioId;
    }
    
    public void setFormularioId(BigDecimal formularioId) {
        this.formularioId = formularioId;
    }
    public String getFlagEstado() {
        return this.flagEstado;
    }
    
    public void setFlagEstado(String flagEstado) {
        this.flagEstado = flagEstado;
    }
    public String getFlagUso() {
        return this.flagUso;
    }
    
    public void setFlagUso(String flagUso) {
        this.flagUso = flagUso;
    }
    public String getDescFormulario() {
        return this.descFormulario;
    }
    
    public void setDescFormulario(String descFormulario) {
        this.descFormulario = descFormulario;
    }
    public String getNombreFormulario() {
        return this.nombreFormulario;
    }
    
    public void setNombreFormulario(String nombreFormulario) {
        this.nombreFormulario = nombreFormulario;
    }
    public BigDecimal getPpsubmenuSubmenuId() {
        return this.ppsubmenuSubmenuId;
    }
    
    public void setPpsubmenuSubmenuId(BigDecimal ppsubmenuSubmenuId) {
        this.ppsubmenuSubmenuId = ppsubmenuSubmenuId;
    }
    public BigDecimal getPpusuarioUsuarioId() {
        return this.ppusuarioUsuarioId;
    }
    
    public void setPpusuarioUsuarioId(BigDecimal ppusuarioUsuarioId) {
        this.ppusuarioUsuarioId = ppusuarioUsuarioId;
    }




}


