package com.cis.paseaproduccionweb.hibernate;
// Generated 19/06/2015 11:30:11 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PpArchivosUso generated by hbm2java
 */
public class PpArchivosUso  implements java.io.Serializable {


     private PpArchivosUsoId id;
     private BigDecimal sistemaId;
     private BigDecimal usuarioId;
     private String nombreArchivo;
     private String descArchivo;

    public PpArchivosUso() {
    }

	
    public PpArchivosUso(PpArchivosUsoId id, BigDecimal sistemaId, BigDecimal usuarioId) {
        this.id = id;
        this.sistemaId = sistemaId;
        this.usuarioId = usuarioId;
    }
    public PpArchivosUso(PpArchivosUsoId id, BigDecimal sistemaId, BigDecimal usuarioId, String nombreArchivo, String descArchivo) {
       this.id = id;
       this.sistemaId = sistemaId;
       this.usuarioId = usuarioId;
       this.nombreArchivo = nombreArchivo;
       this.descArchivo = descArchivo;
    }
   
    public PpArchivosUsoId getId() {
        return this.id;
    }
    
    public void setId(PpArchivosUsoId id) {
        this.id = id;
    }
    public BigDecimal getSistemaId() {
        return this.sistemaId;
    }
    
    public void setSistemaId(BigDecimal sistemaId) {
        this.sistemaId = sistemaId;
    }
    public BigDecimal getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(BigDecimal usuarioId) {
        this.usuarioId = usuarioId;
    }
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }
    public String getDescArchivo() {
        return this.descArchivo;
    }
    
    public void setDescArchivo(String descArchivo) {
        this.descArchivo = descArchivo;
    }




}


