package com.cis.paseaproduccionweb.hibernate;
// Generated 14/07/2015 09:25:56 AM by Hibernate Tools 4.3.1


import java.sql.Blob;

/**
 * PpArchivosPase generated by hbm2java
 */
public class PpArchivosPase  implements java.io.Serializable {


     private long apaseId;
     private String nombreArchivo;
     private Blob archivo;

    public PpArchivosPase() {
    }

	
    public PpArchivosPase(long apaseId) {
        this.apaseId = apaseId;
    }
    public PpArchivosPase(long apaseId, String nombreArchivo, Blob archivo) {
       this.apaseId = apaseId;
       this.nombreArchivo = nombreArchivo;
       this.archivo = archivo;
    }
   
    public long getApaseId() {
        return this.apaseId;
    }
    
    public void setApaseId(long apaseId) {
        this.apaseId = apaseId;
    }
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }
    public Blob getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Blob archivo) {
        this.archivo = archivo;
    }




}


