package com.cis.paseaproduccionweb.hibernate;
// Generated 26/06/2015 10:00:18 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;

/**
 * PpArchivosAprob generated by hbm2java
 */
public class PpArchivosAprob  implements java.io.Serializable {


     private BigDecimal aaprobId;
     private BigDecimal sistemaId;
     private BigDecimal usuarioId;
     private String nombreArchivo;
     private String descArchivo;
     private Blob archivo;
     private String tipo;

    public PpArchivosAprob() {
    }

	
    public PpArchivosAprob(BigDecimal aaprobId, BigDecimal sistemaId, BigDecimal usuarioId) {
        this.aaprobId = aaprobId;
        this.sistemaId = sistemaId;
        this.usuarioId = usuarioId;
    }
    public PpArchivosAprob(BigDecimal aaprobId, BigDecimal sistemaId, BigDecimal usuarioId, String nombreArchivo, String descArchivo, Blob archivo, String tipo) {
       this.aaprobId = aaprobId;
       this.sistemaId = sistemaId;
       this.usuarioId = usuarioId;
       this.nombreArchivo = nombreArchivo;
       this.descArchivo = descArchivo;
       this.archivo = archivo;
       this.tipo = tipo;
    }
   
    public BigDecimal getAaprobId() {
        return this.aaprobId;
    }
    
    public void setAaprobId(BigDecimal aaprobId) {
        this.aaprobId = aaprobId;
    }
    public BigDecimal getSistemaId() {
        return this.sistemaId;
    }
    
    public void setSistemaId(BigDecimal sistemaId) {
        this.sistemaId = sistemaId;
    }
    public BigDecimal getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(BigDecimal usuarioId) {
        this.usuarioId = usuarioId;
    }
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }
    public String getDescArchivo() {
        return this.descArchivo;
    }
    
    public void setDescArchivo(String descArchivo) {
        this.descArchivo = descArchivo;
    }
    public Blob getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Blob archivo) {
        this.archivo = archivo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


