package com.cis.paseaproduccionweb.hibernate;
// Generated 20/07/2015 11:30:52 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * PpHistoriales generated by hbm2java
 */
public class PpHistoriales  implements java.io.Serializable {


     private BigDecimal historialId;
     private PpModulos ppModulos;
     private PpFormularios ppFormularios;
     private Blob archivo;
     private Date fecha;
     private Long nroVersion;
     private String comentarioPase;
     private String comentarioServicios;
     private BigDecimal usuarioId;
     private String nombre;

    public PpHistoriales() {
    }

	
    public PpHistoriales(BigDecimal historialId) {
        this.historialId = historialId;
    }
    public PpHistoriales(BigDecimal historialId, PpModulos ppModulos, PpFormularios ppFormularios, Blob archivo, Date fecha, Long nroVersion, String comentarioPase, String comentarioServicios, BigDecimal usuarioId, String nombre) {
       this.historialId = historialId;
       this.ppModulos = ppModulos;
       this.ppFormularios = ppFormularios;
       this.archivo = archivo;
       this.fecha = fecha;
       this.nroVersion = nroVersion;
       this.comentarioPase = comentarioPase;
       this.comentarioServicios = comentarioServicios;
       this.usuarioId = usuarioId;
       this.nombre = nombre;
    }
   
    public BigDecimal getHistorialId() {
        return this.historialId;
    }
    
    public void setHistorialId(BigDecimal historialId) {
        this.historialId = historialId;
    }
    public PpModulos getPpModulos() {
        return this.ppModulos;
    }
    
    public void setPpModulos(PpModulos ppModulos) {
        this.ppModulos = ppModulos;
    }
    public PpFormularios getPpFormularios() {
        return this.ppFormularios;
    }
    
    public void setPpFormularios(PpFormularios ppFormularios) {
        this.ppFormularios = ppFormularios;
    }
    public Blob getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Blob archivo) {
        this.archivo = archivo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Long getNroVersion() {
        return this.nroVersion;
    }
    
    public void setNroVersion(Long nroVersion) {
        this.nroVersion = nroVersion;
    }
    public String getComentarioPase() {
        return this.comentarioPase;
    }
    
    public void setComentarioPase(String comentarioPase) {
        this.comentarioPase = comentarioPase;
    }
    public String getComentarioServicios() {
        return this.comentarioServicios;
    }
    
    public void setComentarioServicios(String comentarioServicios) {
        this.comentarioServicios = comentarioServicios;
    }
    public BigDecimal getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(BigDecimal usuarioId) {
        this.usuarioId = usuarioId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


