package com.cis.paseaproduccionweb.hibernate;
// Generated 04/08/2015 01:00:43 PM by Hibernate Tools 4.3.1


import java.sql.Blob;

/**
 * PpSentenciasSql generated by hbm2java
 */
public class PpSentenciasSql  implements java.io.Serializable {


     private long setenciasqlId;
     private PpUsuarios ppUsuarios;
     private PpSistemas ppSistemas;
     private String flagEstado;
     private String flagUso;
     private String descSentenciasql;
     private String nombreSentenciasql;
     private String tipo;
     private Blob archivo;

    public PpSentenciasSql() {
    }

	
    public PpSentenciasSql(long setenciasqlId, PpUsuarios ppUsuarios, PpSistemas ppSistemas) {
        this.setenciasqlId = setenciasqlId;
        this.ppUsuarios = ppUsuarios;
        this.ppSistemas = ppSistemas;
    }
    public PpSentenciasSql(long setenciasqlId, PpUsuarios ppUsuarios, PpSistemas ppSistemas, String flagEstado, String flagUso, String descSentenciasql, String nombreSentenciasql, String tipo, Blob archivo) {
       this.setenciasqlId = setenciasqlId;
       this.ppUsuarios = ppUsuarios;
       this.ppSistemas = ppSistemas;
       this.flagEstado = flagEstado;
       this.flagUso = flagUso;
       this.descSentenciasql = descSentenciasql;
       this.nombreSentenciasql = nombreSentenciasql;
       this.tipo = tipo;
       this.archivo = archivo;
    }
   
    public long getSetenciasqlId() {
        return this.setenciasqlId;
    }
    
    public void setSetenciasqlId(long setenciasqlId) {
        this.setenciasqlId = setenciasqlId;
    }
    public PpUsuarios getPpUsuarios() {
        return this.ppUsuarios;
    }
    
    public void setPpUsuarios(PpUsuarios ppUsuarios) {
        this.ppUsuarios = ppUsuarios;
    }
    public PpSistemas getPpSistemas() {
        return this.ppSistemas;
    }
    
    public void setPpSistemas(PpSistemas ppSistemas) {
        this.ppSistemas = ppSistemas;
    }
    public String getFlagEstado() {
        return this.flagEstado;
    }
    
    public void setFlagEstado(String flagEstado) {
        this.flagEstado = flagEstado;
    }
    public String getFlagUso() {
        return this.flagUso;
    }
    
    public void setFlagUso(String flagUso) {
        this.flagUso = flagUso;
    }
    public String getDescSentenciasql() {
        return this.descSentenciasql;
    }
    
    public void setDescSentenciasql(String descSentenciasql) {
        this.descSentenciasql = descSentenciasql;
    }
    public String getNombreSentenciasql() {
        return this.nombreSentenciasql;
    }
    
    public void setNombreSentenciasql(String nombreSentenciasql) {
        this.nombreSentenciasql = nombreSentenciasql;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Blob getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Blob archivo) {
        this.archivo = archivo;
    }




}


