package com.cis.paseaproduccionweb.hibernate;
// Generated 04/08/2015 01:00:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PpSistemas generated by hbm2java
 */
public class PpSistemas  implements java.io.Serializable {


     private BigDecimal sistemaId;
     private String nombreSistema;
     private Set ppSentenciasSqls = new HashSet(0);
     private Set ppHistorialeses = new HashSet(0);

    public PpSistemas() {
    }

	
    public PpSistemas(BigDecimal sistemaId) {
        this.sistemaId = sistemaId;
    }
    public PpSistemas(BigDecimal sistemaId, String nombreSistema, Set ppSentenciasSqls, Set ppHistorialeses) {
       this.sistemaId = sistemaId;
       this.nombreSistema = nombreSistema;
       this.ppSentenciasSqls = ppSentenciasSqls;
       this.ppHistorialeses = ppHistorialeses;
    }
   
    public BigDecimal getSistemaId() {
        return this.sistemaId;
    }
    
    public void setSistemaId(BigDecimal sistemaId) {
        this.sistemaId = sistemaId;
    }
    public String getNombreSistema() {
        return this.nombreSistema;
    }
    
    public void setNombreSistema(String nombreSistema) {
        this.nombreSistema = nombreSistema;
    }
    public Set getPpSentenciasSqls() {
        return this.ppSentenciasSqls;
    }
    
    public void setPpSentenciasSqls(Set ppSentenciasSqls) {
        this.ppSentenciasSqls = ppSentenciasSqls;
    }
    public Set getPpHistorialeses() {
        return this.ppHistorialeses;
    }
    
    public void setPpHistorialeses(Set ppHistorialeses) {
        this.ppHistorialeses = ppHistorialeses;
    }




}


