package com.cis.paseaproduccionweb.hibernate;
// Generated 03/08/2015 12:00:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;

/**
 * PpTempArchaprob generated by hbm2java
 */
public class PpTempArchaprob  implements java.io.Serializable {


     private long tempaaprobId;
     private String nombreArchivo;
     private Blob archivo;
     private Blob archivoFuente;
     private String tipo;
     private String comentarioPase;
     private String comentarioServicios;
     private BigDecimal usuarioId;
     private BigDecimal archivoId;

    public PpTempArchaprob() {
    }

	
    public PpTempArchaprob(long tempaaprobId) {
        this.tempaaprobId = tempaaprobId;
    }
    public PpTempArchaprob(long tempaaprobId, String nombreArchivo, Blob archivo, Blob archivoFuente, String tipo, String comentarioPase, String comentarioServicios, BigDecimal usuarioId, BigDecimal archivoId) {
       this.tempaaprobId = tempaaprobId;
       this.nombreArchivo = nombreArchivo;
       this.archivo = archivo;
       this.archivoFuente = archivoFuente;
       this.tipo = tipo;
       this.comentarioPase = comentarioPase;
       this.comentarioServicios = comentarioServicios;
       this.usuarioId = usuarioId;
       this.archivoId = archivoId;
    }
   
    public long getTempaaprobId() {
        return this.tempaaprobId;
    }
    
    public void setTempaaprobId(long tempaaprobId) {
        this.tempaaprobId = tempaaprobId;
    }
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }
    public Blob getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Blob archivo) {
        this.archivo = archivo;
    }
    public Blob getArchivoFuente() {
        return this.archivoFuente;
    }
    
    public void setArchivoFuente(Blob archivoFuente) {
        this.archivoFuente = archivoFuente;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getComentarioPase() {
        return this.comentarioPase;
    }
    
    public void setComentarioPase(String comentarioPase) {
        this.comentarioPase = comentarioPase;
    }
    public String getComentarioServicios() {
        return this.comentarioServicios;
    }
    
    public void setComentarioServicios(String comentarioServicios) {
        this.comentarioServicios = comentarioServicios;
    }
    public BigDecimal getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(BigDecimal usuarioId) {
        this.usuarioId = usuarioId;
    }
    public BigDecimal getArchivoId() {
        return this.archivoId;
    }
    
    public void setArchivoId(BigDecimal archivoId) {
        this.archivoId = archivoId;
    }




}


